### ISSUE TITLE
can't list when installed local

### ISSUE THREAD

**Issue by rolandg** [balmasi/migrate-mongoose#23]
Hi,
when I install the package only local and run `migrage -d ... list` 
I get following error:
```
module.js:472
    throw err;
    ^

Error: Cannot find module './lib'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/run/media/roland/mData/Dropbox/work/semantify-core/node_modules/.bin/migrate:26:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)


```

**Comment by balmasi** [comment]
This issue should be fixed in 4.0.0
