### ISSUE TITLE
Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by raistlinthewiz** [balmasi/migrate-mongoose#3]
Here is the code i'm trying to run;

```
'use strict';

const config = require('config');
const util = require('util');
const mongodb = require('mongodb');

/**
 * Make any changes you need to make to the database here
 */
exports.up = function up (done) {
	const uri = util.format('mongodb://%s/%s', config.get('database.mongodb.host'), config.get('database.mongodb.name'));

	require('mongodb').connect(uri, function (err, db) {
		if (err) return done(err);

		done();
	});
};

/**
 * Make any changes that UNDO the up function side effects here (if possible)
 */
exports.down = function down (done) {
	done();
};
```

the output

```
λ migrate -d mongodb://localhost/development up
Failed to run migration assign_business_juices due to an error.
Not continuing. Make sure your data is in consistent state
Cannot read property 'then' of undefined
TypeError: Cannot read property 'then' of undefined
    at C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\dist\lib.js:313:51
    at Promise._execute (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\bluebird\js\release\debuggability.js:272:9)
    at Promise._resolveFromExecutor (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\bluebird\js\release\promise.js:473:18)
    at new Promise (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\bluebird\js\release\promise.js:77:14)
    at Migrator._callee2$ (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\dist\lib.js:307:34)
    at tryCatch (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\babel-runtime\regenerator\runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\babel-runtime\regenerator\runtime.js:341:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\babel-runtime\regenerator\runtime.js:121:21)
    at tryCatch (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\babel-runtime\regenerator\runtime.js:88:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\babel-runtime\regenerator\runtime.js:285:24)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\babel-runtime\regenerator\runtime.js:121:21)
    at step (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\babel-runtime\helpers\asyncToGenerator.js:28:20
    at run (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\core-js\library\modules\es6.promise.js:89:22)
    at C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\core-js\library\modules\es6.promise.js:102:28
    at flush (C:\Users\shala\AppData\Roaming\nvm\v6.0.0\node_modules\migrate-mongoose\node_modules\core-js\library\modules\_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by balmasi** [comment]
Hey thanks for reporting this. I'm fixing the bug right now

**Comment by balmasi** [comment]
@raistlinthewiz  I recommend updating to `1.6.4` :)

**Comment by raistlinthewiz** [comment]
fixed thanks
