### ISSUE TITLE
Cannot read property 'server' of null

### ISSUE THREAD

**Issue by andersonlunog** [balmasi/migrate-mongoose#38]
Hello!

I create a free mongodb into https://cloud.mongodb.com/ and I get an URL starting with mongodb+srv.
When I try to instantiate a MigrateMongoose, an error is thrown.

Code:
```javascript
const MigrateMongoose = require("migrate-mongoose");

let migrator = new MigrateMongoose({
  dbConnectionUri: "mongodb+srv://user:pass@cluster0.mongodb.net/DBName?retryWrites=true"
});
```

Error:
```
..\node_modules\migrate-mongoose\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:49
  var server = new Server(this.host, this.port, this.options.server);
                                                             ^
TypeError: Cannot read property 'server' of null
    at NativeConnection.doOpen (..\node_modules\migrate-mongoose\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:49:62)
    at NativeConnection.Connection._open (..\node_modules\migrate-mongoose\node_modules\mongoose\lib\connection.js:694:15)
    at NativeConnection.Connection._openWithoutPromise (..\node_modules\migrate-mongoose\node_modules\mongoose\lib\connection.js:359:8)
    at Mongoose.createConnection (..\node_modules\migrate-mongoose\node_modules\mongoose\lib\index.js:208:32)
    at new Migrator (..\node_modules\migrate-mongoose\dist\lib.js:97:56)
    ...
```

I've tried passing a connection by options, but another error is thrown. I think that just updating the mongoose to the latest version, already solve the problem.

Thanks!

**Comment by balmasi** [comment]
You got it :) Released in 4.0.0 where I've upgraded mongoose to 5.6.3 to support these URI signatures.
